//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftDpadLeftPress
        {
            get
            {
                return SteamVR_Actions.default_LeftDpadLeftPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftDpadRightPress
        {
            get
            {
                return SteamVR_Actions.default_LeftDpadRightPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftDpadUpPress
        {
            get
            {
                return SteamVR_Actions.default_LeftDpadUpPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftDpadDownPress
        {
            get
            {
                return SteamVR_Actions.default_LeftDpadDownPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightDpadLeftPress
        {
            get
            {
                return SteamVR_Actions.default_RightDpadLeftPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightDpadRightPress
        {
            get
            {
                return SteamVR_Actions.default_RightDpadRightPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightDpadDownPress
        {
            get
            {
                return SteamVR_Actions.default_RightDpadDownPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightDpadUpPress
        {
            get
            {
                return SteamVR_Actions.default_RightDpadUpPress;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Stick
        {
            get
            {
                return SteamVR_Actions.default_Stick;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
